---
title: "Art Data Analysis"
author: "Jens Laufer"
date: "17 2 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = T)
```
```{r}
library(tidyverse)
library(glue)
library(mongolite)
library(jsonlite)
library(ggthemes)
library(bbplot)
library(scales)
library(ggrepel)
library(ggcorrplot)
library(forcats)
```

```{r}
con <- mongo("pieces", url="mongodb://localhost/pieces")
```

```{r}
tibble(artist=c("Natural","Heart, Brandon","Status Serigraph (Justin Helton)", "Muck, Jules (Muckrock)","Phantom City Creative","Riveau, Pierre Yves (Pez)"))


# %>%
#   mutate(artist_firstname=replace_na(artist_firstname,"")) %>%
#   unite(artist, artist_firstname, artist_surname, sep=" ")
  
```



```{r}
data <- con$find("{}") %>%
  jsonlite::flatten() %>%
  as_tibble() %>%
  filter(year !=  0) %>%
  separate(size, c("width", "height"), sep = " X ") %>%
  mutate(
    width = as.numeric(width)*2.54,
    height = as.numeric(height)*2.54,
    width_unit = "cm",
    height_unit = "cm",
    run = as.numeric(run),
    area = width * height,
    collections = as.numeric(collections),
    sold = as.numeric(sold)
  ) %>% 
  mutate(released=as.Date(as.POSIXct(as.numeric(released), origin="1970-01-01")))  %>% 
  separate(artist, c("artist_surname", "artist_firstname"), sep=", ") %>% 
  separate(artist_surname, c("artist_surname2", "synonym1"), sep=" \\(") %>%   
  separate(artist_firstname, c("artist_firstname2", "synonym2"), sep=" \\(") %>% 
  unite(artist,artist_firstname2, artist_surname2, sep=" ") %>% 
  mutate(artist=str_replace_all(artist,"NA",""), artist=str_trim(artist)) %>% 
  unite(pseudonym, synonym1, synonym2, sep="") %>% 
  mutate(pseudonym=str_replace_all(pseudonym,"\\)",""),pseudonym=str_replace_all(pseudonym,"NA",""), pseudonym=str_trim(pseudonym))

```



```{r}
data %>% write_csv("art_pieces.csv")
```



```{r}
data %>% 
  glimpse()
```
## Missing Values


```{r}
missingsValues <- data %>% select(-contains("_unit")) %>%
  mutate(row=row_number()) %>% 
  gather(-row, key="feature", value = "value") %>% 
  mutate(isNa=is.na(value)) %>% 
  group_by(feature) %>% 
  mutate(total=n()) %>% 
  ungroup() %>% 
  select(-value) %>% 
  group_by(feature,isNa,total) %>% 
  summarise(n=n()) %>%
  mutate(ratio=n/total*100) %>% 
  select(feature, isNa, ratio)

labels <- missingsValues %>% 
  filter(isNa==F) %>% 
  arrange(ratio) %>% 
  pull(feature)


 missingsValues %>% 
  ggplot(aes(x = feature, y=ratio, fill=isNa, label=paste0(round(ratio, 2),"%")))+
  geom_bar(stat = 'identity') +
  geom_text(position=position_stack(vjust=0.5)) +
  scale_x_discrete(limits=labels) +
  coord_flip()
```


```{r}
data %>% 
  mutate(row=row_number()) %>% 
  gather(-row, key="feature", value = "value") %>% 
  mutate(isNa=is.na(value)) %>% 
  group_by(feature) %>% 
  mutate(total=n()) %>% 
  ungroup() %>% 
  select(-value) %>%
  group_by(feature) %>% 
  slice(228000) %>% 
  ggplot(aes(x=feature, y=row, fill=isNa))+
  geom_raster()+
  coord_flip()
```


## Univariate Analysis

### Continous Variables
```{r fig.height=10, fig.width=20}
data %>% 
  select(-year, -artist_id, -id) %>% 
  select_if(is.numeric) %>% 
  gather(key = "feature", value = "value") %>% 
  filter(!is.na(value)) %>% 
  ggplot(aes(x = value, y = 0)) +
  geom_boxplot() +
  scale_x_continuous(trans="log10", labels = comma) +
  facet_wrap(~feature,scales = "free")
```

## Categorical Variables

```{r fig.height=10, fig.width=20}
data %>%
  select_if(negate(is.numeric)) %>%
  select(-released,-artwork,-artist,-paper) %>%
  select(-contains("_unit")) %>%
  gather() %>%
  group_by(key, value) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  ggplot(aes(x = reorder(value, n), y = n)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(trans = "log10", labels = comma) +
  coord_flip() +
  facet_wrap( ~ key, scales = "free")
```





```{r fig.height=10, fig.width=20}
data %>% 
  mutate(year_bucket=cut(year, 25, dig.lab=4)) %>% 
  group_by(year_bucket) %>%
  summarise(num=n()) %>% 
  ggplot(aes(x = reorder(year_bucket,num), y=num)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = comma, trans = "log10") +
  coord_flip() 
```

```{r}
data %>% 
  group_by(artist) %>%
  summarise(num=n()) %>%
  mutate(label=if_else(num>500, artist, "")) %>% 
  ggplot(aes(x = "", y = num)) +
  geom_boxplot() +
  geom_label_repel(aes(label=label))+
  scale_y_continuous(trans="log10")+
  coord_flip()
```




## Bivariate Analysis

```{r}
data %>% 
  select(-year, -artist_id, -id) %>% 
  select_if(is.numeric) %>% 
  drop_na() %>% 
  cor() %>% 
  ggcorrplot(method = "circle")
```
```{r fig.height=10, fig.width=20}
numericCols <- data %>% 
  select(-year, -artist_id, -id) %>% 
  select_if(is.numeric) %>% 
  colnames()

data %>% 
  select(-year, -artist_id, -id) %>% 
  select_if(is.numeric) %>% 
  gather(-average_price, key="feature", value="value") %>% 
  drop_na() %>% 
  ggplot(aes(x = average_price, y=value)) +
  geom_point(alpha=.2) +
  geom_smooth()+
  scale_y_continuous(trans = "log10") +
  scale_x_continuous(trans = "log10") +
  facet_wrap(~feature, scales = "free")
  
```
```{r}
data %>% 
  arrange(-area) %>% 
  head(10)
```





```{r}
plotQuantQual <-
  function(data,
           var1,
           var2,
           .transVar1 = "log10") {
    data %>%
      drop_na(!!sym(var1),!!sym(var2)) %>%
      ggplot(aes(x = !!sym(var2),
                 y = !!sym(var1))) +
      geom_jitter(alpha = .3, color="#4e79a7") +
      scale_x_discrete(guide = guide_axis(angle = 45),
        limits = data %>%
          group_by(!!sym(var2)) %>%
          summarise(median = median(!!sym(var1), na.rm = T)) %>%
          arrange(-median) %>%
          pull(!!sym(var2))
      ) +
      scale_y_continuous(trans = .transVar1, labels = comma) +
      geom_boxplot(alpha = .7)
  }

plotQuantQuant <-
  function(data,
           var1,
           var2,
           .transVar1 = "identity",
           .transVar2 = "identity") {
    data %>%
      drop_na(!!sym(var1),!!sym(var2)) %>%
      ggplot(aes(x = !!sym(var2),
                 y = !!sym(var1))) +
      geom_point(alpha = .3, color="#4e79a7") +
      scale_y_continuous(trans = .transVar2, labels = comma) +
      scale_x_continuous(trans = .transVar1,
                         labels = comma,
                         guide = guide_axis(angle = 45))
  }


plotQualQual <-
  function(data,
           var1,
           var2,
           .trans = "identity") {
    data %>%
      drop_na(!!sym(var1),!!sym(var2)) %>%
      group_by(!!sym(var1),!!sym(var2)) %>%
      summarise(num = n()) %>%
      ungroup() %>%
      ggplot(aes(
        x = !!sym(var2),
        y = !!sym(var1),
        fill = num
      )) +
      scale_fill_continuous(trans = .trans) +
      scale_x_discrete(guide = guide_axis(angle = 45)) +
      geom_raster()
  }

plotBivariate <- function(data, var1, var2, transVar1="identity", transVar2="identity") {
  var1Numeric <- (data %>% mutate(numeric=is.numeric(!!sym(var1))) %>% pull(numeric))[1]
  var2Numeric <- (data %>% mutate(numeric=is.numeric(!!sym(var2))) %>% pull(numeric))[1]
  
  if (var2Numeric &
      var1Numeric) {
    data %>%
      plotQuantQuant(var1, var2, transVar1, transVar2)
  } else if (!var1Numeric & !var2Numeric) {
    data %>% plotQualQual(var1, var2, transVar1)
  } else if (var1Numeric & !var2Numeric) {
    data %>% plotQuantQual(var1, var2, transVar1)
  } else {
    data %>% plotQuantQual(var2, var1, transVar1)
  }
}

```


```{r}
list(var1=c("class","average_price","average_price","average_price","average_price"),var2=c("technique","technique","class","status","collections"),transVar1=c("log10","log10","log10","log10","log10"), transVar2=c("log10","log10","log10","log10","log10")) %>% 
  pmap(~data %>% 
  plotBivariate(..1,..2,..3,..4))
```

```{r}
data <- data %>%  
  mutate(increase=(highest_price-lowest_price)/lowest_price)
```



```{r}
data %>% 
  filter(lowest_price > 500 & lowest_price < 2000) %>% 
  arrange(-increase) %>% 
  select(id, year, artwork, artist, lowest_price, highest_price, increase, sold)
```


```{r}
data %>% 
  filter(artist=="Mr. Brainwash", str_detect(artwork,"Chaplin")) %>% 
  select(year, artwork, average_price, lowest_price, highest_price, sold, markings) %>% 
  arrange(-average_price)
```



```{r fig.height=10, fig.width=20}
dir.create("images", showWarnings = F)
plotValuableArtists <- function(data, .className) {
  p <- data %>%
    mutate(artist=if_else(pseudonym!="", "{artist} ({pseudonym})" %>% glue(), artist)) %>% 
    filter(lowest_price > 500 &
             lowest_price < 2000,
           increase > 3 & class == .className) %>%
    group_by(artist) %>%
    summarise(avg_increase = mean(increase) * 100) %>%
    ggplot(aes(x = reorder(artist, avg_increase), y = avg_increase)) +
    geom_bar(stat = 'identity', fill = "steelblue") +
    coord_flip() +
    labs(title = 'Valuable Artists in class "{.className}"' %>% glue(), subtitle = "Average increase of price for artist's art pieces in %") +
    bbc_style()
  p %>% finalise_plot(
    source = "Source: https://artventure.me, Data Source: https://expressobeans.com",
    width_pixels = 1000,
    height_pixels = 800,
    save_filepath = "images/{.className}.jpg" %>% glue()
  )
  p
}

plots <- data %>%
  distinct(class) %>%
  pull(class) %>%
  map(~ data %>% plotValuableArtists(..1))

```


